### ISSUE TITLE
umi build 没有生成页面？

### ISSUE THREAD

**Issue by xiaohuoni** [chiaweilee/umi-plugin-md#12]
umi build 没有生成页面？

**Comment by xiaohuoni** [comment]
手动修改 `node_modules/umi-build-dev/lib/routes/getRouteConfigFromDir.js` `const JS_EXTNAMES = ['.js', '.jsx', '.ts', '.tsx', '.md'];` 可以生成

**Comment by chiaweilee** [comment]
https://github.com/chiaweilee/umi-plugin-md/pull/15
