### ISSUE TITLE
求 stylelint-config-ali 和 eslint-plugin-ali 的 npm 发布权限

### ISSUE THREAD

**Issue by bowei-jbw** [chiaweilee/umi-plugin-md#16]
你好，我是阿里 tnpm 包 @ali/stylelint-config-ali 和 eslint-config-ali 的维护者，我看到你在 npm 上发布了 [stylelint-config-ali](https://www.npmjs.com/package/stylelint-config-ali) 和 [eslint-plugin-ali](https://www.npmjs.com/package/eslint-plugin-ali)，可以给我加下发布权限吗？之后我会同步更新这个包。
我的npm账号是 bowei.jbw （bowei.jbw@gmail.com），十分感谢:)

PS.因为不知如何找到你，冒昧在这里提了issue。内网看到你已离职，发了你的私人邮箱但没有响应..感谢:D

**Comment by chiaweilee** [comment]
> 你好，我是阿里 tnpm 包 @ali/stylelint-config-ali 和 eslint-config-ali 的维护者，我看到你在 npm 上发布了 [stylelint-config-ali](https://www.npmjs.com/package/stylelint-config-ali) 和 [eslint-plugin-ali](https://www.npmjs.com/package/eslint-plugin-ali)，可以给我加下发布权限吗？之后我会同步更新这个包。
> 我的npm账号是 bowei.jbw （[bowei.jbw@gmail.com](mailto:bowei.jbw@gmail.com)），十分感谢:)
> 
> PS.因为不知如何找到你，冒昧在这里提了issue。内网看到你已离职，发了你的私人邮箱但没有响应..感谢:D

done!
