### ISSUE TITLE
H1 H2解析完成，h1 没有id，无法导航

### ISSUE THREAD

**Issue by xiaohuoni** [chiaweilee/umi-plugin-md#4]
比如 `#Api`
希望解析为 `<h1 id='Api'>Api</h1>`

**Comment by chiaweilee** [comment]
是需要给 H1 H2 H3 加 锚点（Anchor）吗？

我会在近期迁移过来，从 https://github.com/chiaweilee/vue-markdown-docs/blob/master/src/core/utils.js#L18 https://github.com/chiaweilee/vue-markdown-docs/blob/master/src/core/utils.js#L47

**Comment by xiaohuoni** [comment]
棒，因为我正好在构建官网，所以期望能尽快处理，感谢。
